FROM python:3.12

LABEL maintainer="Arsalan Ayaz"

WORKDIR /code

# Install necessary system dependencies for Protobuf
RUN apt-get update && \
    apt-get install -y protobuf-compiler && \
    rm -rf /var/lib/apt/lists/*

RUN pip install poetry

COPY . /code/

RUN poetry install

EXPOSE 8000

CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]