FROM python:3.12

LABEL maintainer="Arsalan Ayaz"


WORKDIR /code/

RUN pip install poetry

COPY . /code/

RUN poetry install

EXPOSE 8004

CMD ["poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8004", "--reload"]